# Generated by Django 5.1 on 2025-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_videocarousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocarousel',
            name='title',
        ),
        migrations.AlterField(
            model_name='videocarousel',
            name='video_url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
